### ISSUE TITLE
Update Roadmap Images

### ISSUE THREAD

**Issue by erick576** [ENG4000-Team-A/capstone-project#195]
Remove hardware notifications 

add SSL  security to beta 

add UI cleanup to final

**Comment by AlexCHLo** [comment]
Here's the updated version. 
![image](https://user-images.githubusercontent.com/60308758/158472116-c09bfe74-fb76-4f65-9b35-65e83b0d83db.png)

My only concern is that the Hardware section will be empty. So I added one more component for the Hardware section and it is "Integration with OPUS' System".
![image](https://user-images.githubusercontent.com/60308758/158472521-15118676-4bf2-4cf8-9d06-ee6bec3c5882.png)

Please let me know if there any update.
