### ISSUE TITLE
Team Photo

### ISSUE THREAD

**Issue by erick576** [ENG4000-Team-A/capstone-project#255]
- Either A Team Photo or the same type of put together with everyone's faces from the LinkedIn 3 Minute Video
- Mandatory Deliverable

@AlexCHLo if we don't do a team photo you can just take the one from the LinkedIn video

**Comment by AlexCHLo** [comment]
https://docs.google.com/drawings/d/1QCufWGSCBHB_pRF4lcoFy-yjAxH2Ah9wFct0YNUHy2o/edit
