### ISSUE TITLE
set up timer page

### ISSUE THREAD

**Issue by elie0174** [ENG4000-Team-A/capstone-project#53]
ability to set a timer after clicking apply redirects you to the countdown page

**Comment by JesseyH** [comment]
@ChandlerCabrera any idea on how you're going to encode the URL to specify what machines time you are updating? And where are we storing the time info?

**Comment by ChandlerCabrera** [comment]
@JesseyH I tried exploring the different methods of sending data between pages. I don't think we should use local storage or GET, so I've been trying to use POST but having trouble implementing it
