### ISSUE TITLE
finish 3min video 

### ISSUE THREAD

**Issue by elie0174** [ENG4000-Team-A/capstone-project#62]
https://docs.google.com/document/d/1s0moCe8rEe0BdHwgVEsJ4wSOnziiTXLaYgHbZeluWHc/edit

**Comment by AlexCHLo** [comment]
Two more links. Working on the script as well the slide. 

Slide: https://docs.google.com/presentation/d/1G3Fdj0XSDu6lYG5i1CGdGIvqsl3QlAVdOzS0CQBYsK4/edit?usp=sharing
Script: https://docs.google.com/document/d/1NK0sBjsrIFXQTM08aliPJxU7khmO1sU8zgGwIdf64VI/edit?usp=sharing

**Comment by AlexCHLo** [comment]
https://youtu.be/t5bbhck4Q7Y

**Comment by AlexCHLo** [comment]
done I guess. Might reopen if there is something needed to be improved
